apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dotmimblogsite
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dotmimblogsite
    spec:
      containers:
      - name: dotmimblogsite
        image: spertus.azurecr.io/dotmim/dotmimblogsite
        ports:
        - containerPort: 80
        env:
        - name: PostsApiUrl
          value : "http://dotmimpostsapi.default.svc.cluster.local"
---
apiVersion: v1
kind: Service
metadata:
  name: dotmimblogsite
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: dotmimblogsite