apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dotmimpostsapi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dotmimpostsapi
    spec:
      containers:
      - name: dotmimpostsapi
        image: spertus.azurecr.io/dotmim/dotmimpostsapi
        ports:
        - containerPort: 80
          name: port-http
        env:
        - name: ConnectionString
          value : "Data Source=spertus.database.windows.net;Initial Catalog=Blog;UserId=spertus;Password=azerty31$"
---
apiVersion: v1
kind: Service
metadata:
  name: dotmimpostsapi
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: dotmimpostsapi