apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: websample
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: websample
    spec:
      containers:
      - name: websample
        image: spertus.azurecr.io/websample
        ports:
        - containerPort: 80
        # env:
        # - name: PostsApiUrl
        #   value : "http://dotmimpostsapi.default.svc.cluster.local"
---
apiVersion: v1
kind: Service
metadata:
  name: websample
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: websample