// <auto-generated />
using System;
using Dotmim.Common;
using Dotmim.Common.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dotmim.Posts.Api.Migrations
{
    [DbContext(typeof(BlogContext))]
    [Migration("20190305154309_AddSlug")]
    partial class AddSlug
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dotmim.Common.Model.Comment", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<string>("CommentContent");

                    b.Property<string>("Email");

                    b.Property<bool?>("IsAdmin");

                    b.Property<Guid>("PostID");

                    b.Property<DateTime?>("PubDate");

                    b.HasKey("ID");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Dotmim.Common.Model.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("BlogContent")
                        .IsRequired();

                    b.Property<string>("Excerpt");

                    b.Property<bool>("IsPublished");

                    b.Property<DateTime?>("LastModified");

                    b.Property<DateTime?>("PubDate");

                    b.Property<string>("Slug")
                        .HasMaxLength(150);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("53430b5c-d705-4984-88c6-7131de866b1a"),
                            BlogContent = "Welcome !",
                            IsPublished = true,
                            LastModified = new DateTime(2019, 3, 5, 16, 43, 8, 743, DateTimeKind.Local).AddTicks(778),
                            PubDate = new DateTime(2019, 3, 5, 16, 43, 8, 741, DateTimeKind.Local).AddTicks(8388),
                            Slug = "welcome",
                            Title = "Welcome"
                        });
                });

            modelBuilder.Entity("Dotmim.Common.Model.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("PostId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PostId = new Guid("53430b5c-d705-4984-88c6-7131de866b1a"),
                            Title = "#Welcome"
                        });
                });

            modelBuilder.Entity("Dotmim.Common.Model.Tag", b =>
                {
                    b.HasOne("Dotmim.Common.Model.Post", "Post")
                        .WithMany("Tags")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
